tasks:
  - name: test
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: minute
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test2
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: hour
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test3
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: day
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test4
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: week
        value: 1-5
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test5
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: week
        value: 1, 3, 5
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test6
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: month
        value: 1-6
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test7
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: month
        value: 1, 3, 5, 7, 9, 11
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test8
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: quarter
        value: 1-3
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test9
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: quarter
        value: 1, 3, 4
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test10
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: year
        value: 2010-2018
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test11
    schedule:
      type: timing
      time: 00:00:06
      repeat:
        type: year
        value: 2022, 2023
    execution:
      type: python
      file: python/test.py
      param: 



