tasks:
  - name: test
    schedule:
      type: cron
      field: '* * * * *'
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test2
    schedule:
      type: cron
      field: '0 * * * *'
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test3
    schedule:
      type: cron
      field: '0 0 * * *'
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test4
    schedule:
      type: cron
      field: '0 0 * * 1-5'
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test5
    schedule:
      type: cron
      field: '0 0 * * 1,3,5'
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test6
    schedule:
      type: cron
      field: '0 0 1-6 * *'
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test7
    schedule:
      type: cron
      field: '0 0 1,3,5,7,9,11 * *'
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test8
    schedule:
      type: cron
      field: '0 0 1 1-9 *'
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test9
    schedule:
      type: cron
      field: '0 0 1 1-3,7-9,10-12 *'
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test10
    schedule:
      type: cron
      field: '0 0 1 1 *'
  - name: button_test1
    execution:
      type: python
      file: python/test.py
      param: button1
    result:
      name: TEST1,TEST2
