tasks:
  - name: test
    schedule:
      type: cron
      field: '* * * * *'
    execution:
      type: app
      app: t1
      param: -l
  - name: test2
    schedule:
      type: cron
      field: '* * * * *'
    execution:
      type: python
      file: python/test.py
      param: 
  - name: test3
    schedule:
      type: cron
      field: '* * * * *'
    execution:
      type: python
      script: print("test")
  - name: test4
    schedule:
      type: cron
      field: '* * * * *'
    execution:
      type: sql
      file: sql/t1.sql
  - name: test5
    schedule:
      type: cron
      field: '* * * * *'
    execution:
      type: sql
      sql: select COUNT(1) from home_total
  



